controle_estoque/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='login', permanent=False)),
    path('users/', include('users.urls')),
    path('home/', include('home.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home_view, name="home"),
    path('estoque/', views.estoque_view, name="estoque"),
    path('reservas/', views.reservas_view, name='reservas'),
    path('cadastrar/', views.cadastrar_view, name="cadastrar"),
    path('remover/', views.remover_view, name="remover"),
    path('reservar/',views.reservar_view, name="reservar"),
    path('grafico/', views.grafico_view, name='grafico'),
    path('entre_em_contato/', views.entre_em_contato_view, name='entre_em_contato'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User

class Produto(models.Model):
    nome = models.CharField(max_length=100)
    codigo = models.CharField(max_length=50) 
    tipo = models.CharField(max_length=50) 
    data_aquisicao = models.DateField() 
    quantidade = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.nome
    
class Reserva(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField()
    data_reserva = models.DateTimeField(auto_now_add=True)
    data_desejada = models.DateField()

    def __str__(self):
        return f'{self.usuario.username} - {self.produto.nome} - {self.quantidade}'

class Cadastro(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField()
    data_cadastro = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.usuario.username} - {self.produto.nome} - {self.quantidade}'

home/forms.py
from django import forms
from .models import Produto
from .models import Reserva

class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ['nome', 'codigo', 'tipo', 'data_aquisicao', 'quantidade']

class RemoverProdutoForm(forms.Form):
    quantidade = forms.IntegerField(min_value=1, label='Quantidade a ser removida')

    def __init__(self, *args, **kwargs):
        super(RemoverProdutoForm, self).__init__(*args, **kwargs)
        produtos = Produto.objects.all()
        choices = [(produto.id, produto.nome) for produto in produtos]
        self.fields['produto'] = forms.ChoiceField(choices=choices, label='Produto', widget=forms.Select(attrs={'class': 'form-control'}))
        

class ReservaForm(forms.ModelForm):
    class Meta:
        model = Reserva
        fields = ['produto', 'quantidade', 'data_desejada']
        widgets = {
            'data_desejada': forms.DateInput(attrs={'type': 'date'}),
        }

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Produto, Reserva, Cadastro
from django.db.models import Count
from .forms import ReservaForm
from django.core.mail import send_mail
from django.contrib import messages
import openai
from django.conf import settings
from .forms import ProdutoForm
from .forms import RemoverProdutoForm

openai.api_key = settings.OPENAI_API_KEY

# |Tela HOME (NavBar)
@login_required
def home_view(request):
    return render(request, 'home/navbar.html')

# |Tela Estoque de Produtos
@login_required
def estoque_view(request):
    produtos = Produto.objects.all()
    return render(request, 'estoque.html', {'produtos': produtos})

# |Tela Estoque de Produtos Reservados
@login_required
def reservas_view(request):
    produto_id = request.GET.get('produto')
    if produto_id:
        reservas = Reserva.objects.filter(produto_id=produto_id)
    else:
        reservas = Reserva.objects.all()
    produtos = Produto.objects.all()
    return render(request, 'reservas.html', {'reservas': reservas, 'produtos': produtos})

# |Tela Cadastro de Produtos
@login_required
def cadastrar_view(request):
    if request.method == 'POST':
        form = ProdutoForm(request.POST)
        if form.is_valid():
            nome = form.cleaned_data['nome']
            quantidade = form.cleaned_data['quantidade']
            
            produto_existente = Produto.objects.filter(nome=nome).first()
            if produto_existente:
                produto_existente.quantidade += quantidade
                produto_existente.save()
                messages.success(request, f'{quantidade} unidades de {nome} adicionadas ao estoque.')
            else:
                form.save()
                messages.success(request, 'Produto cadastrado com sucesso!')
        else:
            messages.error(request, 'Erro ao cadastrar produto. Verifique os dados e tente novamente.')
    else:
        form = ProdutoForm()
    
    return render(request, 'cadastrar.html', {'form': form})

# |Tela Remover Produtos
@login_required
def remover_view(request):
    produtos = Produto.objects.all()

    if request.method == 'POST':
        form = RemoverProdutoForm(request.POST)
        if form.is_valid():
            produto_id = form.cleaned_data['produto']
            quantidade = form.cleaned_data['quantidade']

            produto = Produto.objects.get(pk=produto_id)

            if quantidade <= produto.quantidade:
                produto.quantidade -= quantidade
                produto.save()

                if produto.quantidade == 0:
                    produto.delete()
                    messages.success(request, f'{quantidade} unidades de {produto.nome} removidas do estoque. O produto foi completamente removido.')
                else:
                    messages.success(request, f'{quantidade} unidades de {produto.nome} removidas do estoque.')
                return redirect('remover')
            else:
                messages.error(request, f'A quantidade a ser removida é maior do que a quantidade disponível ({produto.quantidade}).')
    else:
        form = RemoverProdutoForm()

    return render(request, 'remover.html', {'produtos': produtos, 'form': form})

# | Tela Reservar Produto
@login_required
def reservar_view(request):
    if request.method == 'POST':
        form = ReservaForm(request.POST)
        if form.is_valid():
            produto = form.cleaned_data['produto']
            quantidade = form.cleaned_data['quantidade']
            data_desejada = form.cleaned_data['data_desejada']

            if quantidade <= produto.quantidade:
                produto.quantidade -= quantidade
                produto.save()
                
                Reserva.objects.create(
                    usuario=request.user,
                    produto=produto,
                    quantidade=quantidade,
                    data_desejada=data_desejada
                )
                
                messages.success(request, f'Reserva de {quantidade} unidades de {produto.nome} para {data_desejada} realizada com sucesso!')
                return redirect('reservar')
            else:
                messages.error(request, f'A quantidade desejada é maior do que a quantidade disponível ({produto.quantidade}).')
    else:
        form = ReservaForm()

    return render(request, 'reservar.html', {'form': form})

# | Tela de Grafico
def grafico_view(request):
    tipo_movimentacao = request.GET.get('tipo', 'cadastros')  # Alterado para 'cadastros' por padrão
    
    if tipo_movimentacao == 'cadastros':
        dados = Produto.objects.annotate(total_movimentacao=Count('cadastro')).order_by('-total_movimentacao')[:10]
        titulo = 'Produtos Mais Cadastrados'
    elif tipo_movimentacao == 'reservas':
        dados = Produto.objects.annotate(total_movimentacao=Count('reserva')).order_by('-total_movimentacao')[:10]
        titulo = 'Produtos Mais Reservados'
    else:
        # Se o tipo de movimentação não for nem 'cadastros' nem 'reservas', defina 'dados' como uma lista vazia
        dados = []
        titulo = 'Tipo de movimentação inválido'

    produtos = [produto.nome for produto in dados]
    totais = [produto.total_movimentacao for produto in dados]

    context = {
        'produtos': produtos,
        'totais': totais,
        'titulo': titulo,
    }
    return render(request, 'grafico.html', context)



# |Tela Suporte
@login_required
def entre_em_contato_view(request):
    bot_response = ""
    user_input = ""

    if request.method == 'POST':
        user_input = request.POST.get('user_input')
        user_email = request.POST.get('user_email')

        try:
            response = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "user", "content": user_input}
                ]
            )

            bot_response = response.choices[0].message['content'].strip()

        except openai.error.RateLimitError:
            bot_response = "Você excedeu seu limite de uso da API. Por favor, tente novamente mais tarde ou verifique seu plano e detalhes de faturamento."
        except openai.error.OpenAIError as e:
            bot_response = f"Erro ao acessar a API do OpenAI: {e}"
        except Exception as e:
            bot_response = f"Ocorreu um erro inesperado: {e}"

        if 'send_to_support' in request.POST:
            message = request.POST.get('message')
            try:
                send_mail(
                    'Dúvida de Usuário',
                    f'Dúvida de {user_email}: {message}',
                    settings.EMAIL_HOST_USER,
                    ['extreme.revolution18@gmail.com'],  # E-mail do suporte
                    fail_silently=False,
                )
                messages.success(request, 'Dúvida enviada para o suporte!')
            except Exception as e:
                messages.error(request, f"Ocorreu um erro ao enviar o e-mail: {e}")
            return redirect('entre_em_contato')

    return render(request, 'entre_em_contato.html', {
        'user_input': user_input,
        'bot_response': bot_response,
    })

# |Funções do Bot
@login_required
def send_email_view(request):
    if request.method == 'POST':
        message = request.POST.get('message')
        send_to_support = request.POST.get('send_to_support')
        user_email = request.POST.get('user_email')
        
        if send_to_support:
            try:
                send_mail(
                    'Dúvida de Usuário',
                    f'Dúvida de {user_email}: {message}',
                    settings.EMAIL_HOST_USER,
                    ['extreme.revolution18@gmail.com'],  # E-mail do suporte
                    fail_silently=False,
                )
                messages.success(request, 'Dúvida enviada para o suporte!')
            except Exception as e:
                messages.error(request, f"Ocorreu um erro ao enviar o e-mail: {e}")
            return redirect('entre_em_contato')
        else:
            messages.success(request, 'Obrigado por entrar em contato!')
            return redirect('entre_em_contato')
    else:
        return redirect('entre_em_contato')

@login_required
def solicitar_duvida_view(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        user_email = request.POST.get('user_email')
        message = request.POST.get('message')
        try:
            send_mail(
                'Dúvida de Usuário',
                f'Nome: {name}\nEmail: {user_email}\n\n{message}',
                settings.EMAIL_HOST_USER,
                ['extreme.revolution18@gmail.com'],
                fail_silently=False,
            )
            messages.success(request, 'Dúvida enviada com sucesso!')
        except Exception as e:
            messages.error(request, f"Ocorreu um erro ao enviar o e-mail: {e}")
        return redirect('entre_em_contato')
    return render(request, 'solicitar_duvida.html')

def get_site_info():
    with open('site_info.txt', 'r') as file:
        return file.read()

home/templates/cadastrar.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'home/css/cadastrar.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/navbar.css' %}">
{% endblock 'head' %}

{% block 'body' %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'login' %}">
            <img src="{% static 'geral/img/logo2.gif' %}" alt="Logo" width="50" height="50" class="d-inline-block align-top">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'estoque' %}">Estoque</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cadastrar' %}">Cadastrar Produto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'remover' %}">Remover Produto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Reservar Produto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'entre_em_contato' %}">Entre em Contato</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <h2>Cadastrar Produto</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group">
                <label for="id_nome"><strong>Nome:</strong></label>
                {{ form.nome }}
            </div>
            <div class="form-group">
                <label for="id_quantidade"><strong>Quantidade:</strong></label>
                {{ form.quantidade }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group">
                <label for="id_descricao"><strong>Descrição:</strong></label>
                {{ form.descricao }}
            </div>
        </div>
        <button type="submit" class="btn-submit">Cadastrar</button>
    </form>

    <script>
        {% if messages %}
            {% for message in messages %}
                alert("{{ message }}");
            {% endfor %}
        {% endif %}
    </script>

{% endblock 'body' %}

home/templates/entre_em_contato.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}Entre em Contato{% endblock 'title'%}


{% block 'head' %}
    <link rel="stylesheet" href="{% static 'home/css/entre_em_contato.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/chat.css' %}">
{% endblock 'head' %}

{% block 'body' %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'login' %}">
                <img src="{% static 'geral/img/logo2.gif' %}" alt="Logo" width="50" height="50" class="d-inline-block align-top">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'estoque' %}">Estoque de Produtos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reservas' %}">Produtos Reservados</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cadastrar' %}">Cadastrar Produto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'remover' %}">Remover Produto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reservar' %}">Reservar Produto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'grafico' %}">Gráfico de Movimentações</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'entre_em_contato' %}">Entre em Contato</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="chat-container">

        <!-- <div class="chat-messages" id="chat-messages"></div>

        <div class="chat-input">
            <input type="text" id="user-input" placeholder="Digite sua mensagem...">
            <button onclick="sendMessage()">Enviar</button>
        </div>-->

        <div class="support-box" id="support-box">
            <h3>Deseja entrar em contato com o suporte?</h3>
            <button onclick="showSupportForm()">Sim</button>
            <button onclick="closeChat()">Não</button>
        </div>

        <div class="support-form" id="support-form" style="display: none;">
            <h3>Enviar E-mail para Suporte</h3>
            <input type="email" id="user-email" placeholder="Seu e-mail">
            <textarea id="user-message" placeholder="Sua dúvida"></textarea>
            <button onclick="sendSupportEmail()">Enviar</button>
        </div>
    </div>
    
    <script>
        var csrfToken = '{{ csrf_token }}';
    
        function sendMessage() {
            var userInput = document.getElementById('user-input').value;
            var chatMessages = document.getElementById('chat-messages');
    
            var userMessage = document.createElement('div');
            userMessage.classList.add('chat-message', 'user');
            userMessage.innerHTML = `<div class="message-content">${userInput}</div>`;
            chatMessages.appendChild(userMessage);
    
            document.getElementById('user-input').value = '';
    
            chatMessages.scrollTop = chatMessages.scrollHeight;
    
            fetch('{% url 'entre_em_contato' %}', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrfToken
                },
                body: JSON.stringify({ user_input: userInput })
            })
            .then(response => response.json())
            .then(data => {
                var botMessage = document.createElement('div');
                botMessage.classList.add('chat-message', 'bot');
                botMessage.innerHTML = `<div class="message-content">${data.bot_response}</div>`;
                chatMessages.appendChild(botMessage);
    
                chatMessages.scrollTop = chatMessages.scrollHeight;
    
                if (data.end_conversation) {
                    document.getElementById('support-box').style.display = 'flex';
                }
            })
            .catch(error => console.error('Error:', error));
        }
    
        function showSupportForm() {
            document.getElementById('support-form').style.display = 'block';
        }
    
        function closeChat() {
            document.getElementById('chat-messages').innerHTML = '';
            document.getElementById('support-box').style.display = 'none';
        }
    
        function sendSupportEmail() {
            var userEmail = document.getElementById('user-email').value;
            var userMessage = document.getElementById('user-message').value;
    
            fetch('{% url 'entre_em_contato' %}', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrfToken
                },
                body: JSON.stringify({ user_email: userEmail, message: userMessage, send_to_support: true })
            })
            .then(response => {
                if (response.ok) {
                    alert('E-mail enviado com sucesso!');
                } else {
                    throw new Error('Erro ao enviar o e-mail.');
                }
            })
            .catch(error => console.error('Error:', error));
        }
    </script>
{% endblock 'body' %}

home/templates/estoque.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}Estoque{% endblock 'title' %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'home/css/estoque.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/navbar.css' %}">
{% endblock 'head' %}

{% block 'body' %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'login' %}">
                <img src="{% static 'geral/img/logo2.gif' %}" alt="Logo" width="50" height="50" class="d-inline-block align-top">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'estoque' %}">Estoque de Produtos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reservas' %}">Produtos Reservados</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cadastrar' %}">Cadastrar Produto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'remover' %}">Remover Produto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reservar' %}">Reservar Produto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'grafico' %}">Gráfico de Movimentações</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'entre_em_contato' %}">Entre em Contato</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    <div class="container mt-4">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Nome do Produto</th>
                    <th scope="col">Tipo</th>
                    <th scope="col">Codigo</th>
                    <th scope="col">Quantidade</th>
                    <th scope="col">Data</th>
                </tr>
            </thead>
            <tbody>
                {% for produto in produtos %}
                <tr>
                    <td>{{ produto.nome }}</td>
                    <td>{{ produto.tipo }}</td>
                    <td>{{ produto.codigo }}</td>
                    <td>{{ produto.quantidade }}</td>
                    <td>{{ produto.data_aquisicao }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="3">Nenhum produto disponível.</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock 'body' %}

home/templates/remover.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}Remover Produto{% endblock 'title' %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'home/css/remover.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/navbar.css' %}">
{% endblock 'head' %}

{% block 'body' %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'login' %}">
                <img src="{% static 'geral/img/logo2.gif' %}" alt="Logo" width="50" height="50" class="d-inline-block align-top">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'estoque' %}">Estoque de Produtos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reservas' %}">Produtos Reservados</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cadastrar' %}">Cadastrar Produto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'remover' %}">Remover Produto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reservar' %}">Reservar Produto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'grafico' %}">Gráfico de Movimentações</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'entre_em_contato' %}">Entre em Contato</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <h2>Remover Produto</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_produto"><strong>Produto:</strong></label>
                {{ form.produto }}
            </div>
            <div class="form-group">
                <label for="id_quantidade"><strong>Quantidade a ser removida:</strong></label>
                {{ form.quantidade }}
            </div>
            <button type="submit" class="btn-submit">Remover Produto</button>
        </form>
    
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div class="message {{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
{% endblock 'body' %}

home/templates/reservar.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'home/css/reservar.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/navbar.css' %}">
{% endblock 'head' %}

{% block 'body' %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'login' %}">
            <img src="{% static 'geral/img/logo2.gif' %}" alt="Logo" width="50" height="50" class="d-inline-block align-top">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'estoque' %}">Estoque de Produtos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reservas' %}">Produtos Reservados</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cadastrar' %}">Cadastrar Produto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'remover' %}">Remover Produto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reservar' %}">Reservar Produto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'grafico' %}">Gráfico de Movimentações</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'entre_em_contato' %}">Entre em Contato</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <h2>Reservar Produto</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group">
                <label for="id_produto"><strong>Produto:</strong></label>
                {{ form.produto }}
            </div>
            <div class="form-group">
                <label for="id_quantidade"><strong>Quantidade:</strong></label>
                {{ form.quantidade }}
            </div>
            <div class="form-group">
                <label for="id_data_desejada"><strong>Data Desejada:</strong></label>
                {{ form.data_desejada }}
            </div>
        </div>
        <button type="submit" class="btn-submit">Reservar</button>
    </form>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div class="message {{ message.tags }}">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
</div>

{% endblock 'body' %}